/** @type {import('tailwindcss').Config} */

module.exports = {
    content: ['src/**/*.{tsx,ts,jsx,js}', './App.{tsx,ts,jsx,js}'],
    presets: [require('nativewind/preset')],
    theme: {
        extend: {
            fontFamily: {
                'plex-bold': 'IBMPlexSansKR-Bold',
                'plex-medium': 'IBMPlexSansKR-Medium',
                'plex-regular': 'IBMPlexSansKR-Regular',
                'plex-light': 'IBMPlexSansKR-Light',
                'plex-thin': 'IBMPlexSansKR-Thin',
                'plex-extralight': 'IBMPlexSansKR-ExtraLight',
                'plex-semibold': 'IBMPlexSansKR-SemiBold',
                aldrich: 'Aldrich-Regular',
                osd: 'VCROSTMono',
            },
            colors: {
                'vivid-green': '#B4FD2E',
                'light-green': '#eafc88',
                'vivid-purple': '#75316b',
                'light-purple': '#984E8F',
                'vivid-red': '#E12D39',
                'light-red': '#F96D6D',
                'vivid-blue': '#2D95BF',
                'light-blue': '#4DB8FF',
                'vivid-yellow': '#FFD43B',
                'light-yellow': '#FFDD78',
                'vivid-orange': '#FF5100',
                'light-orange': '#FF7C00',
                'vivid-pink': '#FF0074',
                'light-pink': '#FF4A8A',
                'vivid-cyan': '#00D8FF',
                'light-cyan': '#6EE7FF',
                'vivid-indigo': '#4E3DFF',
                'light-indigo': '#7D6BFF',
                'vivid-teal': '#00FFD8',
                'light-teal': '#6EF1FF',
                'vivid-lime': '#C8FF00',
                'light-lime': '#E7FF6E',
                'vivid-gray': '#D8D8D8',
                'light-gray': '#F1F1F1',
                'dark-gray': '#363636',
                black: '#000000',
                white: '#FFFFFF',
                background: '#000000',
                'light-background': '#363636',
            },
            keyframes: {
                'to-right': {
                    '0%': {transform: 'translateX(0)'},
                    '100%': {transform: 'translateX(10px)'},
                },
                'fromt-top': {
                    '0%': {transform: 'translateY(-10px)', opacity: 0},
                    '100%': {transform: 'translateY(0px)', opacity: 1},
                },
            },
            animation: {
                'to-right': 'to-right 1s ease-in-out infinite alternate',
                'from-top': 'fromt-top 0.15s ease-in-out',
            },
        },
        fontSize: {
            // regenerate text sizes without line-height
            xxs: '.625rem',
            xs: '.75rem',
            sm: '.875rem',
            base: '1rem',
            lg: '1.125rem',
            xl: '1.25rem',
            '2xl': '1.5rem',
            '3xl': '1.875rem',
            '4xl': '2.25rem',
            '5xl': '3rem',
            '6xl': '4rem',
            '7xl': '5rem',
            '8xl': '6rem',
            '9xl': '8rem',
        },
    },
    plugins: [],
};
